### ISSUE TITLE
Website Issue [URGENT]

### ISSUE THREAD

**Issue by djhenjin** [FlingOS/FlingOS#106]
Hey, even if you aren't actively working on this project right now, you are definitely going to want to take care of an issue with your website.

Using Safari 11.1.2 on Mac OSX I noticed that my processor was running at very nearly 100% capacity due to something janky going on with your site. I was able to narrow the issue down to the styles used in the site, though I cannot be more specific than that. 

This also appears to happen in Chrome as well, but to a far lesser extent.

It seems like the styles are being invalidated too quickly and they are being re-computed and re-drawn more often than they should be.

**Comment by EdNutting** [comment]
Hi, Thanks for bringing this to my attention.

Unfortunately I have no idea what may be causing this. In Google Chrome, Firefox and Edge on Windows these issues don't occur for me(0.1% usage after initial load of various pages even with scrolling around etc.)

Is there a specific page this occurred on? Can you open developer tools and use the performance/profiling to point to something (script or specific styles?)? There's very few scripts in the site all of which look fine to me.

Please be aware that the site is HTTP not HTTPS so is liable to be man-in-the-middle attacked by viruses on your PC, home network or otherwise. Most routers are insecure.

I'll keep looking into it to see if I can find a cause. It may also have been a rogue Google ad - there's been more of those lately.

**Comment by EdNutting** [comment]
I've uploaded a slightly older version of the site with the Google ads and analytics removed (due to Google's change in adsense policy they stopped paying out on the ads for small sites anyway so it's pointless having them there.)

Hopefully this will mitigate some risks.

**Comment by EdNutting** [comment]
I've had this checked by 2 friends on different Apple and Windows devices. Still no reproduction. Without further information I'm going to have to assume this is fixed.
