### ISSUE TITLE
Documentation Project Fails to Load.

### ISSUE THREAD

**Issue by DaveOsDev** [FlingOS/FlingOS#84]
As far as I am aware - Documentation is no longer created through Sandcastle. So, not having Sandcastle Installed prevents the documentation folder from being added to the solution.

**Reccomend**: Remove Documentation that relies on Sandcastle.

**Comment by EdNutting** [comment]
Not quite. The online technical docs are generated using Sandcastle from the XML docs in the code. FlingOS has it's own custom version of Sandcastle (forked somewhere...I probably ought to add it as a submodule - I'll do that next week) so that the Markdown generation works properly. 

The online reference / explanatory articles are written in Markdown by hand (of course).
