### ISSUE TITLE
i want to implement malloc in tutorials examples

### ISSUE THREAD

**Issue by ahmedfme** [FlingOS/FlingOS#85]
i have learned a lot from the tutorials provided by you in c .
i am going now to implement malloc function and i wonder how the kernel could allocate memory for malloc , i.e sbrk() function..
i appeciate if you provide me a suitable code for sbrk() to sho how to allocate free space in the heap.

**Comment by EdNutting** [comment]
Hi,
Sorry for the delay in getting back to you. I'm glad you have learnt a lot from the tutorials. 

Malloc and Sbrk are two separate things. Malloc deals with dividing up a prorgram's Heap into chunks for use as structures/objects. If a program runs out of space for its heap, Malloc may call Sbrk to expand the space available to the program. 

Sbrk is a system call which uses the Kernel's memory management system. The Kernel's memory management system controls the entire address space (or multiple address spaces - probably one per program) along with the physical memory (and any page files). The memory management system can allocate more memory to a program. This is what Sbrk requests from the kernel. 

So, you need to decide what it is you're trying to do. If you've just finished the tutorials, you're probably looking for two things:
1. A heap within the kernel to use for temporary (small) structures/objects (i.e. allocations)
2. A memory management system to handle the address spaces

The first is the most important and does not use system calls. You will need to implement some form of heap (e.g. a [bitmap heap](http://wiki.osdev.org/User:Pancakes/BitmapHeapImplementation) which is the easiest/simplest) and then you can use that to alloc/free memory for use within the main kernel process.

The second (which underpins Sbrk) requires you to implement essentially a virtual memory manager. This constructs a paged memory setup for each process (inc. kernel process) and manages assigning physical pages to different processes along with the virtual addresses for those pages. When a process switch occurs, the address space must be switched (which is ~80% of what a process switch is). Sbrk merely calls the memory manager to get more pages and have them appended (in the virtual address range) to the program's existing data pages.

I do not have C code available but the FlingOS code in [Kernel.FOS_System](https://github.com/FlingOS/FlingOS/tree/develop/Kernel/Libraries/Kernel.FOS_System) for [Heap](https://github.com/FlingOS/FlingOS/blob/develop/Kernel/Libraries/Kernel.FOS_System/Heap.cs) is a C# version of a Bitmap heap (adapted from the OSDev C version). The [Kernel.Hardware.VirtMem](https://github.com/FlingOS/FlingOS/tree/develop/Kernel/Libraries/Kernel.Hardware/VirtMem) namespace and [Kernel.Hardware.VirtMemManager](https://github.com/FlingOS/FlingOS/blob/develop/Kernel/Libraries/Kernel.Hardware/VirtMemManager.cs) may also prove useful to you. I suspect you probably don't have processes/process switching yet, so I suggest you concentrate on that before trying to work out things like system calls, since the latter cannot really exist without the former. You will probably want to use pre-emptive scheduling, so make sure you have the [Timer (PIT)](http://www.flingos.co.uk/docs/reference/Programmable-Interval-Timer/) interrupt working and configured to a slow (~5 or 10ms) rate generator to make testing easier).

The following articles may also be of help:
1. [FlingOS - Memory](http://www.flingos.co.uk/docs/reference/Memory/) (and associated sub-topics)
2. [FlingOS - Typical Design Routes](http://www.flingos.co.uk/docs/reference/Typical-Design-Routes/) (as guidance on the design routes you can choose to take. Also see the Getting Started article). 

I hope this helps. Cheers,
Ed
